"IMAGE","FILE","TASK",ERROR"
"anchore/test_images:allthethings_v1","/usr/lib/python2.7/dist-packages/setuptools/cli-32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:allthethings_v1","/usr/lib/python2.7/dist-packages/setuptools/cli-64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:allthethings_v1","/usr/lib/python2.7/dist-packages/setuptools/cli.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:allthethings_v1","/usr/lib/python2.7/dist-packages/setuptools/gui-32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:allthethings_v1","/usr/lib/python2.7/dist-packages/setuptools/gui-64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:allthethings_v1","/usr/lib/python2.7/dist-packages/setuptools/gui.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:allthethings_v1","/usr/local/lib/node_modules/npm/node_modules/term-size/vendor/macos/term-size","cargo-auditable-binary-cataloger","rust cataloger: unable to read dependency information: unknown file format"
"anchore/test_images:allthethings_v1","/usr/local/lib/node_modules/npm/node_modules/term-size/vendor/macos/term-size","unknowns-labeler","no package identified in executable file"
"anchore/test_images:allthethings_v1","/var/lib/dpkg/info/bash.preinst","unknowns-labeler","no package identified in executable file"
