"IMAGE","FILE","TASK",ERROR"
"anchore/test_images:fedora31-oscap","/usr/lib/python3.7/site-packages/pip/_vendor/distlib/t32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:fedora31-oscap","/usr/lib/python3.7/site-packages/pip/_vendor/distlib/t64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:fedora31-oscap","/usr/lib/python3.7/site-packages/pip/_vendor/distlib/w32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:fedora31-oscap","/usr/lib/python3.7/site-packages/pip/_vendor/distlib/w64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
