"IMAGE","FILE","TASK",ERROR"
"anchore/test_images:python_sha_reg","/usr/local/lib/libpython3.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_asyncio.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_bisect.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_blake2.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_bz2.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_codecs_cn.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_codecs_hk.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_codecs_iso2022.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_codecs_jp.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_codecs_kr.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_codecs_tw.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_contextvars.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_crypt.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_csv.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_ctypes.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_ctypes_test.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_curses.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_curses_panel.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_datetime.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_dbm.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_decimal.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_elementtree.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_gdbm.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_hashlib.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_heapq.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_json.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_lsprof.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_lzma.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_md5.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_multibytecodec.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_multiprocessing.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_opcode.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_pickle.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_queue.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_random.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_sha1.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_sha256.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_sha3.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_sha512.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_socket.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_sqlite3.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_ssl.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_struct.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_testbuffer.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_testcapi.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_testimportmultiple.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_testmultiphase.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_tkinter.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_uuid.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/_xxtestfuzz.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/array.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/audioop.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/binascii.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/cmath.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/fcntl.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/grp.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/math.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/mmap.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/nis.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/ossaudiodev.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/parser.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/pyexpat.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/readline.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/resource.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/select.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/spwd.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/syslog.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/termios.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/unicodedata.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/xxlimited.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/lib-dynload/zlib.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/PIL/_imaging.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/PIL/_imagingcms.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/PIL/_imagingft.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/PIL/_imagingmath.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/PIL/_imagingmorph.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/PIL/_imagingtk.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/PIL/_webp.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/Pillow.libs/libXau-00ec42fe.so.6.0.0","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/Pillow.libs/libfreetype-804dfcff.so.6.18.0","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/Pillow.libs/libharfbuzz-a69be65e.so.0.30000.0","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/Pillow.libs/libjpeg-183418da.so.9.4.0","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/Pillow.libs/liblcms2-035b9744.so.2.0.12","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/Pillow.libs/liblzma-d540a118.so.5.2.5","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/Pillow.libs/libopenjp2-430a98fc.so.2.4.0","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/Pillow.libs/libpng16-213e245f.so.16.37.0","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/Pillow.libs/libtiff-9ffe9659.so.5.7.0","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/Pillow.libs/libwebp-d8a3db66.so.7.1.2","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/Pillow.libs/libwebpdemux-f117ddb4.so.2.0.8","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/Pillow.libs/libwebpmux-fe44437b.so.3.0.7","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/Pillow.libs/libxcb-1122e22b.so.1.1.0","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/Pillow.libs/libz-dd453c56.so.1.2.11","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/catboost/_catboost.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/kiwisolver.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/matplotlib/_c_internal_utils.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/matplotlib/_contour.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/matplotlib/_image.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/matplotlib/_path.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/matplotlib/_qhull.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/matplotlib/_tri.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/matplotlib/_ttconv.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/matplotlib/backends/_backend_agg.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/matplotlib/backends/_tkagg.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/matplotlib/backends/web_backend/package.json","javascript-package-cataloger","skipping package.json with insufficient package information: name: '', version: ''"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/matplotlib/ft2font.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/numpy.libs/libgfortran-2e0d59d6.so.5.0.0","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/numpy.libs/libopenblasp-r0-2d23e62b.3.17.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/numpy.libs/libquadmath-2d0c479f.so.0.0.0","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/numpy/core/_multiarray_tests.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/numpy/core/_operand_flag_tests.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/numpy/core/_rational_tests.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/numpy/core/_simd.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/numpy/core/_struct_ufunc_tests.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/numpy/core/_umath_tests.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/numpy/fft/_pocketfft_internal.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/numpy/linalg/_umath_linalg.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/numpy/linalg/lapack_lite.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/numpy/random/_bounded_integers.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/numpy/random/_common.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/numpy/random/_generator.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/numpy/random/_mt19937.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/numpy/random/_pcg64.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/numpy/random/_philox.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/numpy/random/_sfc64.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/numpy/random/bit_generator.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/numpy/random/mtrand.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/algos.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/arrays.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/groupby.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/hashing.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/hashtable.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/index.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/indexing.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/internals.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/interval.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/join.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/json.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/lib.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/missing.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/ops.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/ops_dispatch.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/parsers.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/properties.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/reduction.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/reshape.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/sparse.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/testing.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/tslib.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/tslibs/base.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/tslibs/ccalendar.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/tslibs/conversion.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/tslibs/dtypes.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/tslibs/fields.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/tslibs/nattype.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/tslibs/np_datetime.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/tslibs/offsets.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/tslibs/parsing.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/tslibs/period.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/tslibs/strptime.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/tslibs/timedeltas.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/tslibs/timestamps.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/tslibs/timezones.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/tslibs/tzconversion.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/tslibs/vectorized.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/window/aggregations.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/window/indexers.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/_libs/writers.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pandas/io/sas/_sas.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pip/_vendor/distlib/t32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pip/_vendor/distlib/t32.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pip/_vendor/distlib/t64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pip/_vendor/distlib/t64.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pip/_vendor/distlib/w32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pip/_vendor/distlib/w32.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pip/_vendor/distlib/w64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/pip/_vendor/distlib/w64.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy.libs/libgfortran-ed201abd.so.3.0.0","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy.libs/libopenblasp-r0-085ca80a.3.9.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/_lib/_ccallback_c.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/_lib/_fpumode.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/_lib/_test_ccallback.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/_lib/_test_deprecation_call.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/_lib/_test_deprecation_def.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/_lib/_uarray/_uarray.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/_lib/messagestream.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/cluster/_hierarchy.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/cluster/_optimal_leaf_ordering.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/cluster/_vq.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/fft/_pocketfft/pypocketfft.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/fftpack/convolve.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/integrate/_dop.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/integrate/_odepack.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/integrate/_quadpack.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/integrate/_test_multivariate.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/integrate/_test_odeint_banded.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/integrate/lsoda.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/integrate/vode.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/interpolate/_bspl.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/interpolate/_fitpack.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/interpolate/_ppoly.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/interpolate/_rbfinterp_pythran.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/interpolate/dfitpack.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/interpolate/interpnd.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/io/_test_fortran.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/io/matlab/mio5_utils.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/io/matlab/mio_utils.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/io/matlab/streams.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/linalg/_decomp_update.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/linalg/_fblas.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/linalg/_flapack.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/linalg/_flinalg.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/linalg/_interpolative.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/linalg/_matfuncs_sqrtm_triu.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/linalg/_solve_toeplitz.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/linalg/cython_blas.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/linalg/cython_lapack.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/ndimage/_ctest.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/ndimage/_cytest.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/ndimage/_nd_image.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/ndimage/_ni_label.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/odr/__odrpack.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/optimize/__nnls.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/optimize/_bglu_dense.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/optimize/_cobyla.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/optimize/_group_columns.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/optimize/_highs/_highs_constants.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/optimize/_highs/_highs_wrapper.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/optimize/_lbfgsb.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/optimize/_lsap_module.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/optimize/_lsq/givens_elimination.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/optimize/_minpack.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/optimize/_slsqp.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/optimize/_trlib/_trlib.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/optimize/_zeros.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/optimize/cython_optimize/_zeros.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/optimize/minpack2.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/optimize/moduleTNC.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/signal/_max_len_seq_inner.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/signal/_peak_finding_utils.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/signal/_sosfilt.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/signal/_spectral.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/signal/_upfirdn_apply.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/signal/sigtools.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/signal/spline.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/sparse/_csparsetools.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/sparse/_sparsetools.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/sparse/csgraph/_flow.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/sparse/csgraph/_matching.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/sparse/csgraph/_min_spanning_tree.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/sparse/csgraph/_reordering.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/sparse/csgraph/_shortest_path.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/sparse/csgraph/_tools.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/sparse/csgraph/_traversal.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/sparse/linalg/dsolve/_superlu.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/arpack/_arpack.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/sparse/linalg/isolve/_iterative.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/spatial/_distance_pybind.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/spatial/_distance_wrap.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/spatial/_hausdorff.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/spatial/_voronoi.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/spatial/ckdtree.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/spatial/qhull.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/spatial/transform/rotation.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/special/_comb.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/special/_ellip_harm_2.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/special/_test_round.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/special/_ufuncs.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/special/_ufuncs_cxx.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/special/cython_special.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/special/specfun.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/stats/_boost/beta_ufunc.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/stats/_boost/binom_ufunc.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/stats/_boost/nbinom_ufunc.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/stats/_qmc_cy.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/stats/_sobol.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/stats/_stats.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/stats/biasedurn.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/stats/mvn.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/scipy/stats/statlib.cpython-37m-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/setuptools/cli-32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/setuptools/cli-32.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/setuptools/cli-64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/setuptools/cli-64.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/setuptools/cli.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/setuptools/cli.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/setuptools/gui-32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/setuptools/gui-32.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/setuptools/gui-64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/setuptools/gui-64.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/setuptools/gui.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:python_sha_reg","/usr/local/lib/python3.7/site-packages/setuptools/gui.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python_sha_reg","/var/lib/dpkg/info/bash.preinst","unknowns-labeler","no package identified in executable file"
