"FILE","ERROR"
"/plone/buildout-cache/eggs/cp38/AccessControl-4.4-py3.8-linux-x86_64.egg/AccessControl/cAccessControl.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/Acquisition-4.13-py3.8-linux-x86_64.egg/Acquisition/_Acquisition.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/BTrees-4.11.3-py3.8-linux-x86_64.egg/BTrees/_IFBTree.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/BTrees-4.11.3-py3.8-linux-x86_64.egg/BTrees/_IIBTree.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/BTrees-4.11.3-py3.8-linux-x86_64.egg/BTrees/_IOBTree.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/BTrees-4.11.3-py3.8-linux-x86_64.egg/BTrees/_IUBTree.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/BTrees-4.11.3-py3.8-linux-x86_64.egg/BTrees/_LFBTree.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/BTrees-4.11.3-py3.8-linux-x86_64.egg/BTrees/_LLBTree.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/BTrees-4.11.3-py3.8-linux-x86_64.egg/BTrees/_LOBTree.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/BTrees-4.11.3-py3.8-linux-x86_64.egg/BTrees/_LQBTree.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/BTrees-4.11.3-py3.8-linux-x86_64.egg/BTrees/_OIBTree.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/BTrees-4.11.3-py3.8-linux-x86_64.egg/BTrees/_OLBTree.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/BTrees-4.11.3-py3.8-linux-x86_64.egg/BTrees/_OOBTree.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/BTrees-4.11.3-py3.8-linux-x86_64.egg/BTrees/_OQBTree.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/BTrees-4.11.3-py3.8-linux-x86_64.egg/BTrees/_OUBTree.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/BTrees-4.11.3-py3.8-linux-x86_64.egg/BTrees/_QFBTree.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/BTrees-4.11.3-py3.8-linux-x86_64.egg/BTrees/_QLBTree.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/BTrees-4.11.3-py3.8-linux-x86_64.egg/BTrees/_QOBTree.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/BTrees-4.11.3-py3.8-linux-x86_64.egg/BTrees/_QQBTree.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/BTrees-4.11.3-py3.8-linux-x86_64.egg/BTrees/_UFBTree.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/BTrees-4.11.3-py3.8-linux-x86_64.egg/BTrees/_UIBTree.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/BTrees-4.11.3-py3.8-linux-x86_64.egg/BTrees/_UOBTree.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/BTrees-4.11.3-py3.8-linux-x86_64.egg/BTrees/_UUBTree.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/BTrees-4.11.3-py3.8-linux-x86_64.egg/BTrees/_fsBTree.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/ExtensionClass-4.9-py3.8-linux-x86_64.egg/ComputedAttribute/_ComputedAttribute.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/ExtensionClass-4.9-py3.8-linux-x86_64.egg/ExtensionClass/_ExtensionClass.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/ExtensionClass-4.9-py3.8-linux-x86_64.egg/MethodObject/_MethodObject.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/MarkupSafe-2.1.1-py3.8-linux-x86_64.egg/markupsafe/_speedups.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/Persistence-3.6-py3.8-linux-x86_64.egg/Persistence/_Persistence.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/Pillow-6.2.2-py3.8-linux-x86_64.egg/PIL/.libs/libfreetype-69f25d5e.so.6.17.1","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/Pillow-6.2.2-py3.8-linux-x86_64.egg/PIL/.libs/libjpeg-3b10b538.so.9.3.0","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/Pillow-6.2.2-py3.8-linux-x86_64.egg/PIL/.libs/liblcms2-a6801db4.so.2.0.8","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/Pillow-6.2.2-py3.8-linux-x86_64.egg/PIL/.libs/liblzma-6cd627ed.so.5.2.4","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/Pillow-6.2.2-py3.8-linux-x86_64.egg/PIL/.libs/libopenjp2-b3d7668a.so.2.3.1","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/Pillow-6.2.2-py3.8-linux-x86_64.egg/PIL/.libs/libpng16-bedcb7ea.so.16.37.0","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/Pillow-6.2.2-py3.8-linux-x86_64.egg/PIL/.libs/libtiff-bd1961ca.so.5.5.0","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/Pillow-6.2.2-py3.8-linux-x86_64.egg/PIL/.libs/libwebp-3a2aeecf.so.7.0.5","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/Pillow-6.2.2-py3.8-linux-x86_64.egg/PIL/.libs/libwebpdemux-e9ec482e.so.2.0.6","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/Pillow-6.2.2-py3.8-linux-x86_64.egg/PIL/.libs/libwebpmux-40630b44.so.3.0.4","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/Pillow-6.2.2-py3.8-linux-x86_64.egg/PIL/.libs/libz-a147dcb0.so.1.2.3","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/Pillow-6.2.2-py3.8-linux-x86_64.egg/PIL/_imaging.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/Pillow-6.2.2-py3.8-linux-x86_64.egg/PIL/_imagingcms.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/Pillow-6.2.2-py3.8-linux-x86_64.egg/PIL/_imagingft.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/Pillow-6.2.2-py3.8-linux-x86_64.egg/PIL/_imagingmath.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/Pillow-6.2.2-py3.8-linux-x86_64.egg/PIL/_imagingmorph.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/Pillow-6.2.2-py3.8-linux-x86_64.egg/PIL/_imagingtk.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/Pillow-6.2.2-py3.8-linux-x86_64.egg/PIL/_webp.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/PyYAML-5.4.1-py3.8-linux-x86_64.egg/yaml/_yaml.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/RelStorage-3.4.5-py3.8-linux-x86_64.egg/relstorage/cache/cache.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/cffi-1.15.1-py3.8-linux-x86_64.egg/_cffi_backend.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/cx_Oracle-8.3.0-py3.8-linux-x86_64.egg/cx_Oracle.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/lxml-4.8.0-py3.8-linux-x86_64.egg/lxml/_elementpath.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/lxml-4.8.0-py3.8-linux-x86_64.egg/lxml/builder.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/lxml-4.8.0-py3.8-linux-x86_64.egg/lxml/etree.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/lxml-4.8.0-py3.8-linux-x86_64.egg/lxml/html/clean.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/lxml-4.8.0-py3.8-linux-x86_64.egg/lxml/html/diff.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/lxml-4.8.0-py3.8-linux-x86_64.egg/lxml/objectify.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/lxml-4.8.0-py3.8-linux-x86_64.egg/lxml/sax.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/mysqlclient-2.1.1-py3.8-linux-x86_64.egg/MySQLdb/_mysql.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/perfmetrics-3.3.0-py3.8-linux-x86_64.egg/perfmetrics/_metric.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/persistent-4.9.3-py3.8-linux-x86_64.egg/persistent/_ring.abi3.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/persistent-4.9.3-py3.8-linux-x86_64.egg/persistent/_timestamp.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/persistent-4.9.3-py3.8-linux-x86_64.egg/persistent/cPersistence.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/persistent-4.9.3-py3.8-linux-x86_64.egg/persistent/cPickleCache.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/psycopg2-2.9.3-py3.8-linux-x86_64.egg/psycopg2/_psycopg.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/pyScss-1.3.7-py3.8-linux-x86_64.egg/scss/grammar/_scanner.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/pyrsistent-0.15.7-py3.8-linux-x86_64.egg/pvectorc.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/python_ldap-3.4.2-py3.8-linux-x86_64.egg/_ldap.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/regex-2023.6.3-py3.8-linux-x86_64.egg/regex/_regex.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/simplejson-3.18.1-py3.8-linux-x86_64.egg/simplejson/_speedups.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/zodbpickle-2.6-py3.8-linux-x86_64.egg/zodbpickle/_pickle.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/zope.container-5.1-py3.8-linux-x86_64.egg/zope/container/_zope_container_contained.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/zope.hookable-5.4-py3.8-linux-x86_64.egg/zope/hookable/_zope_hookable.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/zope.i18nmessageid-5.1.1-py3.8-linux-x86_64.egg/zope/i18nmessageid/_zope_i18nmessageid_message.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/zope.interface-5.5.2-py3.8-linux-x86_64.egg/zope/interface/_zope_interface_coptimizations.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/zope.proxy-4.6.1-py3.8-linux-x86_64.egg/zope/proxy/_zope_proxy_proxy.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/zope.security-5.8-py3.8-linux-x86_64.egg/zope/security/_proxy.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/plone/buildout-cache/eggs/cp38/zope.security-5.8-py3.8-linux-x86_64.egg/zope/security/_zope_security_checker.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/libpython3.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_asyncio.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_bisect.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_blake2.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_bz2.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_codecs_cn.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_codecs_hk.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_codecs_iso2022.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_codecs_jp.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_codecs_kr.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_codecs_tw.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_contextvars.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_crypt.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_csv.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_ctypes_test.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_curses.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_curses_panel.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_datetime.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_dbm.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_decimal.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_elementtree.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_gdbm.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_hashlib.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_heapq.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_json.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_lsprof.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_lzma.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_md5.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_multibytecodec.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_multiprocessing.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_opcode.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_pickle.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_posixshmem.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_posixsubprocess.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_queue.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_random.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_sha1.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_sha256.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_sha3.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_sha512.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_socket.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_sqlite3.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_ssl.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_statistics.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_struct.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_testbuffer.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_testcapi.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_testimportmultiple.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_testinternalcapi.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_testmultiphase.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_tkinter.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_uuid.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_xxsubinterpreters.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/_xxtestfuzz.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/array.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/audioop.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/binascii.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/cmath.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/fcntl.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/grp.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/math.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/mmap.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/nis.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/ossaudiodev.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/parser.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/pyexpat.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/readline.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/resource.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/select.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/spwd.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/syslog.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/termios.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/unicodedata.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/xxlimited.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/lib-dynload/zlib.cpython-38-x86_64-linux-gnu.so","no package identified in executable file"
"/usr/local/lib/python3.8/site-packages/setuptools/cli-32.exe","unable to find PE name in file"
"/usr/local/lib/python3.8/site-packages/setuptools/cli-32.exe","no package identified in executable file"
"/usr/local/lib/python3.8/site-packages/setuptools/cli-64.exe","unable to find PE name in file"
"/usr/local/lib/python3.8/site-packages/setuptools/cli-64.exe","no package identified in executable file"
"/usr/local/lib/python3.8/site-packages/setuptools/cli-arm64.exe","unable to find PE name in file"
"/usr/local/lib/python3.8/site-packages/setuptools/cli-arm64.exe","no package identified in executable file"
"/usr/local/lib/python3.8/site-packages/setuptools/cli.exe","unable to find PE name in file"
"/usr/local/lib/python3.8/site-packages/setuptools/cli.exe","no package identified in executable file"
"/usr/local/lib/python3.8/site-packages/setuptools/gui-32.exe","unable to find PE name in file"
"/usr/local/lib/python3.8/site-packages/setuptools/gui-32.exe","no package identified in executable file"
"/usr/local/lib/python3.8/site-packages/setuptools/gui-64.exe","unable to find PE name in file"
"/usr/local/lib/python3.8/site-packages/setuptools/gui-64.exe","no package identified in executable file"
"/usr/local/lib/python3.8/site-packages/setuptools/gui-arm64.exe","unable to find PE name in file"
"/usr/local/lib/python3.8/site-packages/setuptools/gui-arm64.exe","no package identified in executable file"
"/usr/local/lib/python3.8/site-packages/setuptools/gui.exe","unable to find PE name in file"
"/usr/local/lib/python3.8/site-packages/setuptools/gui.exe","no package identified in executable file"
"/var/lib/dpkg/info/bash.preinst","no package identified in executable file"
