"IMAGE","FILE","TASK",ERROR"
"anchore/test_images:python-slim-buster","/usr/local/lib/libpython3.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_asyncio.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_bisect.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_blake2.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_bz2.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_codecs_cn.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_codecs_hk.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_codecs_iso2022.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_codecs_jp.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_codecs_kr.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_codecs_tw.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_contextvars.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_crypt.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_csv.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_ctypes.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_ctypes_test.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_curses.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_curses_panel.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_datetime.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_decimal.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_elementtree.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_gdbm.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_hashlib.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_heapq.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_json.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_lsprof.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_lzma.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_md5.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_multibytecodec.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_multiprocessing.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_opcode.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_pickle.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_posixshmem.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_posixsubprocess.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_queue.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_random.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_sha1.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_sha256.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_sha3.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_sha512.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_socket.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_sqlite3.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_ssl.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_statistics.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_struct.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_testbuffer.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_testcapi.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_testimportmultiple.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_testinternalcapi.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_testmultiphase.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_tkinter.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_uuid.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_xxsubinterpreters.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_xxtestfuzz.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/_zoneinfo.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/array.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/audioop.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/binascii.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/cmath.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/fcntl.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/grp.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/math.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/mmap.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/nis.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/ossaudiodev.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/parser.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/pyexpat.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/readline.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/resource.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/select.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/spwd.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/syslog.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/termios.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/unicodedata.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/xxlimited.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/lib-dynload/zlib.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/site-packages/pip/_vendor/distlib/t32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/site-packages/pip/_vendor/distlib/t32.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/site-packages/pip/_vendor/distlib/t64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/site-packages/pip/_vendor/distlib/t64.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/site-packages/pip/_vendor/distlib/w32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/site-packages/pip/_vendor/distlib/w32.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/site-packages/pip/_vendor/distlib/w64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/site-packages/pip/_vendor/distlib/w64.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/site-packages/setuptools/cli-32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/site-packages/setuptools/cli-32.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/site-packages/setuptools/cli-64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/site-packages/setuptools/cli-64.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/site-packages/setuptools/cli.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/site-packages/setuptools/cli.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/site-packages/setuptools/gui-32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/site-packages/setuptools/gui-32.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/site-packages/setuptools/gui-64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/site-packages/setuptools/gui-64.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/site-packages/setuptools/gui.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:python-slim-buster","/usr/local/lib/python3.9/site-packages/setuptools/gui.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:python-slim-buster","/var/lib/dpkg/info/bash.preinst","unknowns-labeler","no package identified in executable file"
