"IMAGE","FILE","TASK",ERROR"
"sentry:latest","/usr/local/bin/gosu","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/bin/tini","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/bin/uwsgi","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/distutils/command/wininst-6.0.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"sentry:latest","/usr/local/lib/python2.7/distutils/command/wininst-6.0.exe","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/distutils/command/wininst-7.1.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"sentry:latest","/usr/local/lib/python2.7/distutils/command/wininst-7.1.exe","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/distutils/command/wininst-8.0.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"sentry:latest","/usr/local/lib/python2.7/distutils/command/wininst-8.0.exe","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/distutils/command/wininst-9.0-amd64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"sentry:latest","/usr/local/lib/python2.7/distutils/command/wininst-9.0-amd64.exe","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/distutils/command/wininst-9.0.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"sentry:latest","/usr/local/lib/python2.7/distutils/command/wininst-9.0.exe","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_bisect.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_bsddb.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_codecs_cn.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_codecs_hk.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_codecs_iso2022.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_codecs_jp.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_codecs_kr.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_codecs_tw.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_collections.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_csv.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_ctypes.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_ctypes_test.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_curses.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_curses_panel.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_elementtree.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_functools.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_hashlib.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_heapq.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_hotshot.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_io.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_json.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_locale.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_lsprof.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_multibytecodec.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_multiprocessing.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_random.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_socket.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_sqlite3.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_ssl.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_struct.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_testcapi.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/_tkinter.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/array.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/audioop.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/binascii.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/bz2.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/cPickle.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/cStringIO.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/cmath.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/crypt.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/datetime.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/dbm.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/fcntl.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/future_builtins.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/gdbm.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/grp.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/itertools.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/linuxaudiodev.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/math.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/mmap.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/nis.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/operator.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/ossaudiodev.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/parser.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/pyexpat.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/readline.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/resource.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/select.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/spwd.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/strop.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/syslog.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/termios.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/time.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/unicodedata.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/lib-dynload/zlib.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/.libs_cffi_backend/libffi-0ff6ce5e.so.6.0.4","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/PIL/.libs/libfreetype-c8a1f873.so.6.14.0","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/PIL/.libs/libjpeg-bcb94a84.so.9.2.0","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/PIL/.libs/liblcms2-488a716d.so.2.0.8","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/PIL/.libs/liblzma-f444c404.so.5.2.2","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/PIL/.libs/libopenjp2-59185378.so.2.1.0","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/PIL/.libs/libpng16-4b619e46.so.16.25.0","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/PIL/.libs/libtiff-fa49d64f.so.5.2.6","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/PIL/.libs/libwebp-ff8209c3.so.7.0.0","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/PIL/.libs/libwebpdemux-3d2fbd88.so.2.0.2","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/PIL/.libs/libwebpmux-7b696cfc.so.3.0.0","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/PIL/.libs/libz-a147dcb0.so.1.2.3","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/PIL/_imaging.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/PIL/_imagingcms.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/PIL/_imagingft.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/PIL/_imagingmath.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/PIL/_imagingmorph.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/PIL/_imagingtk.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/PIL/_webp.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/_billiard.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/_cffi_backend.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/_librabbitmq.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/_yaml.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_constant_time.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_padding.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/hiredis/hiredis.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/lxml/_elementpath.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/lxml/builder.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/lxml/etree.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/lxml/html/clean.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/lxml/html/diff.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/lxml/objectify.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/lxml/sax.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/maxminddb/extension.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/mmh3.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/msgpack/_cmsgpack.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/t32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/t32.exe","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/t64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/t64.exe","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/w32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/w32.exe","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/w64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/pip/_vendor/distlib/w64.exe","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/psycopg2/.libs/libcom_err-beb60336.so.2.1","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/psycopg2/.libs/libcrypto-c1fa9491.so.1.0.2q","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/psycopg2/.libs/libgssapi_krb5-174f8956.so.2.2","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/psycopg2/.libs/libk5crypto-622ef25b.so.3.1","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/psycopg2/.libs/libkeyutils-1-ff31573b.2.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/psycopg2/.libs/libkrb5-fb0d2caa.so.3.3","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/psycopg2/.libs/libkrb5support-d7ce89d4.so.0.1","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/psycopg2/.libs/liblber-2-d7edd0dc.4.so.2.10.7","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/psycopg2/.libs/libldap_r-2-9270213a.4.so.2.10.7","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/psycopg2/.libs/libpq-bd31fe2b.so.5.11","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/psycopg2/.libs/libsasl2-e96a0dbf.so.2.0.22","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/psycopg2/.libs/libselinux-cf8f9094.so.1","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/psycopg2/.libs/libsepol-b4f5b513.so.1","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/psycopg2/.libs/libssl-c0c2ede4.so.1.0.2q","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/psycopg2/.libs/libz-a147dcb0.so.1.2.3","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/psycopg2/_psycopg.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/amd64/x_ignore_nofocus.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/x86/x_ignore_nofocus.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/semaphore/_lowlevel__lib.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/setproctitle.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/setuptools/cli-32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/setuptools/cli-32.exe","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/setuptools/cli-64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/setuptools/cli-64.exe","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/setuptools/cli.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/setuptools/cli.exe","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/setuptools/gui-32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/setuptools/gui-32.exe","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/setuptools/gui-64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/setuptools/gui-64.exe","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/setuptools/gui.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/setuptools/gui.exe","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/simplejson/_speedups.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/usr/local/lib/python2.7/site-packages/symbolic/_lowlevel__lib.so","unknowns-labeler","no package identified in executable file"
"sentry:latest","/var/lib/dpkg/info/bash.preinst","unknowns-labeler","no package identified in executable file"
