"IMAGE","FILE","TASK",ERROR"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/_brotli.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/aiohttp/_helpers.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/aiohttp/_http_parser.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/aiohttp/_http_writer.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/aiohttp/_websocket.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/bson/_cbson.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/couchbase/pycbc_core.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/frozenlist/_frozenlist.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/greenlet/_greenlet.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/greenlet/tests/_test_extension.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/greenlet/tests/_test_extension_cpp.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/markupsafe/_speedups.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/multidict/_multidict.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/pymongo/_cmessage.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/setuptools/cli-32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/setuptools/cli-32.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/setuptools/cli-64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/setuptools/cli-64.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/setuptools/cli-arm64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/setuptools/cli-arm64.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/setuptools/cli.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/setuptools/cli.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/setuptools/gui-32.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/setuptools/gui-32.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/setuptools/gui-64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/setuptools/gui-64.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/setuptools/gui-arm64.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/setuptools/gui-arm64.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/setuptools/gui.exe","dotnet-portable-executable-cataloger","unable to find PE name in file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/setuptools/gui.exe","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/sqlalchemy/cimmutabledict.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/sqlalchemy/cprocessors.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/sqlalchemy/cresultproxy.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/wrapt/_wrappers.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/yaml/_yaml.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
"anchore/test_images:grype-quality-python-d89207b","/usr/local/packages/python/yarl/_quoting_c.cpython-39-x86_64-linux-gnu.so","unknowns-labeler","no package identified in executable file"
